---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vf-device-plugin-config
  namespace: kube-system
data:
  config.yml: |

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: vf-device-plugin
  namespace: kube-system
spec:
  selector:
    matchLabels:
      name: vf-device-plugin
  template:
    metadata:
      labels:
        name: vf-device-plugin
    spec:
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      containers:
      - name: vf-device-plugin
        image: ctr.0x.pt/kraud/vf-device-plugin:xxxVERSIONxxx
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
        volumeMounts:
          - name: device-plugins
            mountPath: /var/lib/kubelet/device-plugins
          - name: dev
            mountPath: /dev
          - name: sys
            mountPath: /sys
          - name: config
            mountPath: /root/config
      volumes:
        - name: device-plugins
          hostPath:
            path: /var/lib/kubelet/device-plugins
        - name: dev
          hostPath:
            path: /dev
        - name: sys
          hostPath:
            path: /sys
        - name: config
          configMap:
            name: vf-device-plugin-config
